CREATE TABLE client (
    enitity_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE product (
    enitity_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNIT_PRICE NUMERIC(20,2)
);

CREATE TABLE order (
    enitity_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDER_DATE TIMESTAMP,
    ORDER_TOTAL NUMERIC(20,2)
);

CREATE TABLE order_product (
    enitity_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES ORDER (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    c INTEGER
);